# 사용할 JDK 버전을 명시한다.
FROM openjdk:17-jdk

# 빌드가 완료된 jar 파일의 위치를 환경변수로 등록한다.
ARG JAR_FILE=build/libs/modu-menu-0.0.1-SNAPSHOT.jar

# 컨테이너 진입 시 /app으로 이동하도록 한다.
WORKDIR /app

# jar 파일을 이미지 내부에 설정한 이름으로 추가한다.
COPY ${JAR_FILE} ./modu-menu.jar

# 컨테이너가 실행될 때 반드시 실행할 명령어를 입력한다.
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=prod", "-Duser.timezone=Asia/Seoul", "modu-menu.jar"]