spring:
  profiles:
    active:
      - test

springdoc: # ref: https://springdoc.org/#properties
  version: '@project.version@'
  api-docs:
    path: /api-docs # spring boot 웹 애플리케이션의 api를 OpenAPI 3을 이용하여 json 형식화 한 것의 경로
  default-consumes-media-type: application/json # request media type의 기본값
  default-produces-media-type: application/json # response media type의 기본값
  swagger-ui:
    operations-sorter: alpha # 태그 내 각 api의 정렬 기준(default: 컨트롤러 내에서 정의한 api 메서드 순, alpha: 사전 순, method: http 메서드 순)
    tags-sorter: alpha # 태그 정렬 기준
    path: /swagger-ui.html # Swagger HTML 문서 경로(default: ./swagger-ui/)
    disable-swagger-default-url: true # swagger-ui default url인 petstore html 문서 비활성화 여부
    display-query-params-without-oauth2: true # json화 된 config 파일 대신 파라미터를 이용하여 swagger-ui에 접근하도록 함
  paths-to-match: # OpenAPI 3로 문서화할 api path 리스트
    - /api/**