server:
  port: 8000
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: modu
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100 # oneToMany 사용시 in 쿼리 자동으로 작성
    open-in-view: false # OSIV = false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    '[modu.menu]': DEBUG
    '[org.hibernate.type]': TRACE # 쿼리 ?에 주입된 값 콘솔에 출력


springdoc: # ref: https://springdoc.org/#properties
  version: '@project.version@'
  api-docs:
    path: /api-docs # spring boot 웹 애플리케이션의 api를 OpenAPI 3을 이용하여 json 형식화 한 것의 경로
  default-consumes-media-type: application/json # request media type의 기본값
  default-produces-media-type: application/json # response media type의 기본값
  swagger-ui:
    operations-sorter: alpha # 태그 내 각 api의 정렬 기준(default: 컨트롤러 내에서 정의한 api 메서드 순, alpha: 사전 순, method: http 메서드 순)
    tags-sorter: alpha # 태그 정렬 기준
    path: /swagger-ui.html # Swagger HTML 문서 경로(default: ./swagger-ui/)
    disable-swagger-default-url: true # swagger-ui default url인 petstore html 문서 비활성화 여부
    display-query-params-without-oauth2: true # json화 된 config 파일 대신 파라미터를 이용하여 swagger-ui에 접근하도록 함
  paths-to-match: # OpenAPI 3로 문서화할 api path 리스트
    - /api/**