server:
  port: 5000
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  datasource:
    url: jdbc:mysql://modu-menu-db.c9s4i8io2u83.ap-northeast-2.rds.amazonaws.com:3306/modu_menu_db?useSSL=false # MySQL 8.x부터 useSSL=false 추가 필요
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      default_batch_fetch_size: 100
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    '[modu.menu]': INFO

oauth2:
  user:
    kakao:
      client-id: 2a2a821ddfebdb0b1ee1e056b51d2105 # 앱 REST API 키
      client-secret: 1PTjnSQ9AYjiJ85AVhcO00qOJmdybjrK # 테스트용 Secret키
      redirect-uri: https://localhost:8080/oauth/redirect # 인가 코드를 전달받을 서비스 서버의 URI
  provider:
    kakao:
      token-uri: https://kauth.kakao.com/oauth/token