name: 모두의 회식 CI

# 동적 변수 설정
env:
  RESOURCE_PATH: ./src/main/resources/application-prod.yml
  RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
  RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
  ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
  REFRESH_SECRET: ${{ secrets.REFRESH_SECRET }}

on:
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: repository에서 코드를 가져온다.
        uses: actions/checkout@v4

      - name: OpenJDK 17을 세팅한다.
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 빌드에 사용하고자 하는 yml 파일에 환경변수 값을 주입한다.
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ env.RESOURCE_PATH }}
        env:
          spring.datasource.username: ${{ env.RDS_USERNAME }}
          spring.datasource.password: ${{ env.RDS_PASSWORD }}
          jwt.access-secret: ${{ env.ACCESS_SECRET }}
          jwt.refresh-secret: ${{ env.REFRESH_SECRET }}

      - name: Gradle 명령 실행을 위한 권한을 부여한다.
        run: chmod +x ./gradlew

      - name: Gradle 빌드를 수행한다.
        run: ./gradlew build